### ISSUE TITLE
Building on OpenJDK 11 fails

### ISSUE THREAD

**Issue by jgriss** [spectra-cluster/spectra-cluster-2#82]
This issue comes up on CircleCI and on Travis. When using Java > 9 the build throws the following error:
```
Could not resolve dependencies for project org.spectra.cluster:spectra-cluster:jar:2.0.0-SNAPSHOT: Could not find artifact com.sun.java:tools:jar:11.0.2 at specified path /usr/lib/jvm/java-11-openjdk-amd64/../lib/tools.jar
```

**Comment by ypriverol** [comment]
Should we remove for now 9.0 ?

**Comment by jgriss** [comment]
I found the reason (after a lot of searching) here https://stackoverflow.com/questions/53707666/how-to-get-tools-jar-for-openjdk-11-on-windows:

> It was removed in JDK 9.
> JEP 220 removed the well-known and frequently-referenced JARs rt.jar and tools.jar. According to it's description, "The class and resource files previously stored in lib/rt.jar, lib/tools.jar, lib/dt.jar, and various other internal jar files will now be stored in a more efficient format in implementation-specific files in the lib directory.

This means that some of our libraries uses `tools.jar` - I'm now in the process of finding out which one. We should update it or remove it

**Comment by jgriss** [comment]
It's here:

```
+- net.openhft:chronicle-map:jar:3.16.4:compile
[INFO] |  +- net.openhft:chronicle-core:jar:1.16.28:compile
[INFO] |  +- net.openhft:chronicle-values:jar:2.16.1:compile
[INFO] |  |  +- com.sun.java:tools:jar:1.8.0_201:system
```

**Comment by jgriss** [comment]
Fixing this now. We have a lot of unused dependencies in our pom file. Removing them.

**Comment by jgriss** [comment]
@ypriverol Could you try changing the dependency of pgiotk to ChronicleMap 3.17.1
The current one used requires Java 8

**Comment by ypriverol** [comment]
Done!!!

**Comment by jgriss** [comment]
I've re-started the travis tests with OpenJDK 10 and 11 - let's see

**Comment by jgriss** [comment]
Still failing. As long as ChronicleMap depends on Java 8 this cannot be fixed.
